apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
  namespace: upspin
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: upspin
subsets:
- addresses:
  - ip: 192.168.2.6
  ports:
  - port: 1
