apiVersion: v1
kind: PersistentVolume
metadata:
  name: upspin-conf-pv
  namespace: upspin
spec:
  capacity:
    storage: 300Gi
  accessModes:
  - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-cluster
    path: gv0/Kubernetes/Upspin/config
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
