kind: Service
apiVersion: v1
metadata:
  labels:
    app: upspin
  name: upspin-tcp
  namespace: upspin
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 4080
    name: web
    protocol: TCP
  - port: 443
    targetPort: 443
    nodePort: 4443
    name: ssl
    protocol: TCP
  selector:
    app: upspin
  type: LoadBalancer
